<?php

// Only these business fields expose values. Unknown fields retain a change
// marker, so adding a database column cannot accidentally expose a credential.
return [
    'modules' => [
        'User' => ['users', '用户管理', 'v2_user'], 'Order' => ['orders', '订单管理', 'v2_order'],
        'Plan' => ['plans', '订阅套餐', 'v2_plan'], 'Coupon' => ['coupons', '优惠券', 'v2_coupon'],
        'Giftcard' => ['giftcards', '礼品卡', 'v2_giftcard'], 'Notice' => ['notices', '公告管理', 'v2_notice'],
        'Knowledge' => ['knowledge', '知识库', 'v2_knowledge'], 'Ticket' => ['tickets', '工单管理', 'v2_ticket'],
        'Config' => ['settings', '系统设置', 'settings'], 'Reward' => ['rewards', '签到与娱乐', 'settings'],
        'Theme' => ['themes', '主题设置', 'theme'], 'Payment' => ['payments', '支付设置', 'v2_payment'],
        'Rate' => ['rates', '动态倍率', 'v2_rate_rule'], 'ExternalSource' => ['external', '外部订阅源', 'v2_external_source'],
        'RiskTrace' => ['risk', '订阅溯源', 'v2_user'], 'RiskSharedIp' => ['risk', '多账号同 IP', 'v2_user'],
        'SubscribeCleanGateway' => ['risk', '订阅清洗网关', 'v2_subscribe_block_rule'],
        'Reseller' => ['resellers', '倒卖商管理', 'v2_reseller_account'], 'Stat' => ['statistics', '统计查询', ''],
        'System' => ['system', '系统运行信息', ''], 'Security' => ['security', '账号与安全审计', ''],
        'Group' => ['nodes', '节点权限组', 'v2_server_group'], 'Route' => ['nodes', '节点路由', 'v2_server_route'],
        'Manage' => ['nodes', '节点管理', ''], 'Auth' => ['security', '管理员登录', 'v2_user'],
        'TwoFactor' => ['security', '二步验证', 'v2_user_two_factor'],
    ],
    'tables' => [
        'v2_user' => '用户', 'v2_subscription' => '用户订阅', 'v2_order' => '订单', 'v2_plan' => '套餐',
        'v2_coupon' => '优惠券', 'v2_giftcard' => '礼品卡', 'v2_notice' => '公告', 'v2_knowledge' => '知识库',
        'v2_ticket' => '工单', 'v2_ticket_message' => '工单回复', 'v2_payment' => '支付方式',
        'v2_server_group' => '节点权限组', 'v2_server_route' => '节点路由', 'v2_invite_code' => '邀请码',
        'v2_commission_log' => '佣金记录', 'v2_mail_log' => '邮件发送记录',
        'v2_balance_log' => '余额流水', 'v2_payment_attempt' => '支付尝试',
        'v2_rate_setting' => '倍率全局设置', 'v2_rate_rule' => '倍率时段规则', 'v2_rate_policy' => '倍率场景策略',
        'v2_rate_node_policy' => '节点倍率绑定', 'v2_rate_policy_state' => '倍率策略状态',
        'v2_external_source' => '外部订阅源', 'v2_external_node' => '外部节点',
        'v2_subscribe_block_rule' => '订阅阻断规则', 'v2_subscribe_block_event' => '订阅阻断事件',
        'v2_subscribe_account_risk' => '账号风险记录', 'v2_user_two_factor' => '二步验证',
        'v2_reseller_account' => '倒卖商账号', 'v2_reseller_review_log' => '倒卖商审核记录',
        'v2_reseller_plan_template' => '倒卖商套餐模板', 'v2_reseller_order' => '倒卖商订单',
        'v2_reseller_shared_subscription' => '共享订阅', 'v2_reseller_shared_subscription_member' => '共享订阅成员',
        'settings' => '系统配置', 'theme' => '主题配置',
    ],
    'fields' => [
        'id' => '编号', 'email' => '邮箱', 'name' => '名称', 'title' => '标题', 'subject' => '主题',
        'description' => '说明', 'remark' => '备注', 'reason' => '原因', 'note' => '处理说明',
        'remarks' => '备注', 'notes' => '处理说明', 'discount' => '专属折扣', 'commission_type' => '佣金发放方式',
        'capacity_limit' => '购买人数限制', 'knowledge_ids' => '可见知识条目', 'knowledge_category_ids' => '可见知识分类',
        'plan_ids' => '适用套餐', 'periods' => '适用周期', 'alias' => '别名', 'notify_domain' => '通知域名',
        'listen_ip' => '监听地址', 'insecure' => '跳过证书验证', 'encryption' => '加密方式',
        'padding_scheme' => '填充方案', 'zero_rtt_handshake' => '零往返握手', 'pinned_peer_cert_sha256' => '证书固定指纹',
        'order_id' => '订单', 'attempt_no' => '支付尝试编号', 'order_amount_minor' => '订单金额',
        'gateway_amount_minor' => '支付渠道金额', 'gateway_currency' => '支付币种', 'gateway_transaction_id' => '支付流水号',
        'balance_before' => '变动前余额', 'balance_after' => '变动后余额', 'amount' => '变动金额', 'source_type' => '关联来源类型',
        'user_id' => '用户', 'subscription_id' => '订阅', 'primary_subscription_id' => '主订阅',
        'is_primary' => '主订阅标记', 'node_user_id' => '节点用户编号', 'source_order_id' => '来源订单',
        'purchase_type' => '购买类型', 'reset_at' => '下次重置时间', 'last_reset_at' => '上次重置时间',
        'plan_id' => '套餐', 'base_plan_id' => '基础套餐', 'group_id' => '权限组', 'group_ids' => '权限组',
        'route_id' => '路由', 'route_ids' => '路由', 'invite_user_id' => '邀请人', 'invite_user_email' => '邀请人邮箱',
        'balance' => '余额', 'commission_balance' => '佣金余额', 'commission_rate' => '佣金比例',
        'actual_commission_balance' => '实际发放佣金', 'total_amount' => '订单金额', 'paid_amount_minor' => '实付金额',
        'order_amount' => '订单金额', 'get_amount' => '获得佣金', 'handling_amount' => '手续费',
        'discount_amount' => '优惠金额', 'surplus_amount' => '折抵金额', 'refund_amount' => '退款金额', 'balance_amount' => '余额抵扣',
        'month_price' => '月付价格', 'quarter_price' => '季付价格', 'half_year_price' => '半年价格',
        'year_price' => '年付价格', 'two_year_price' => '两年价格', 'three_year_price' => '三年价格',
        'onetime_price' => '一次性价格', 'reset_price' => '流量重置价格',
        'transfer_enable' => '总流量', 'u' => '上传流量', 'd' => '下载流量', 'speed_limit' => '限速',
        'device_limit' => '设备数限制', 'expired_at' => '到期时间', 'started_at' => '开始时间',
        'ended_at' => '结束时间', 'expires_at' => '失效时间', 'paid_at' => '支付时间', 'fetched_at' => '抓取时间',
        'banned' => '账号停用', 'admin_role' => '管理员身份', 'is_admin' => '后台权限', 'is_staff' => '旧客服权限',
        'show' => '显示状态', 'renew' => '允许续费', 'enabled' => '启用状态', 'enable' => '启用状态',
        'status' => '状态', 'reply_status' => '回复状态', 'commission_status' => '佣金状态',
        'sort' => '排序', 'trade_no' => '订单号', 'callback_no' => '支付流水号', 'period' => '购买周期',
        'type' => '类型', 'value' => '数值', 'limit_use' => '可用次数', 'limit_use_with_user' => '每用户可用次数',
        'limit_plan_ids' => '适用套餐', 'limit_period' => '适用周期', 'used_user_ids' => '已使用用户',
        'language' => '语言', 'category' => '分类', 'img_url' => '封面图片', 'tags' => '标签', 'level' => '优先级',
        'host' => '节点地址', 'server_port' => '服务端端口', 'port' => '端口', 'ports' => '端口范围',
        'parent_id' => '父节点', 'rate' => '流量倍率', 'network' => '传输方式', 'protocol' => '协议',
        'tls' => 'TLS', 'sni' => '服务器名称', 'server_name' => '服务器名称', 'host_header' => '请求主机',
        'path' => '传输路径', 'service_name' => '服务名称', 'allow_insecure' => '允许不安全连接',
        'fingerprint' => 'TLS 指纹', 'public_key' => '公钥', 'short_id' => '短 ID', 'flow' => '流控',
        'cipher' => '加密方式', 'version' => '版本', 'alpn' => 'ALPN', 'congestion_control' => '拥塞控制',
        'up_mbps' => '上行速率', 'down_mbps' => '下行速率', 'disable_sni' => '关闭 SNI',
        'listen' => '监听地址', 'listen_port' => '监听端口', 'obfs' => '混淆方式',
        'obfs_host' => '混淆主机', 'skip_cert_verify' => '跳过证书校验', 'dest' => '目标地址',
        'action' => '路由动作', 'match' => '匹配条件', 'outbound' => '出站设置',
        'source_id' => '订阅源', 'url' => '地址', 'node_count' => '节点数量', 'last_fetch_at' => '最后刷新时间',
        'last_status' => '最后刷新状态', 'node_type' => '节点协议', 'node_id' => '节点',
        'setting_key' => '设置项', 'setting_value' => '设置值', 'scope' => '作用范围',
        'mode' => '模式', 'policy_id' => '场景策略', 'timezone' => '时区', 'days' => '生效日期',
        'start_time' => '开始时刻', 'end_time' => '结束时刻', 'priority' => '优先级',
        'multiplier' => '倍率', 'rate_multiplier' => '倍率', 'fallback_rate' => '备用倍率',
        'instant_mbps' => '瞬时带宽阈值', 'sustained_mbps' => '持续带宽阈值', 'burst_exempt_minutes' => '突发豁免分钟',
        'stack_minutes' => '叠加触发分钟', 'stack_multiplier' => '叠加倍率', 'decay_step' => '恢复步长',
        'start_minute' => '开始时刻', 'end_minute' => '结束时刻', 'obfs_password' => '混淆密码',
        'serverName' => '服务器名称', 'allowInsecure' => '允许不安全连接', 'serviceName' => '服务名称',
        'shortIds' => '短 ID 列表', 'publicKey' => '公钥', 'dest' => '目标地址', 'server' => '服务器地址',
        'packet_encoding' => '数据包编码', 'udp_relay_mode' => 'UDP 转发方式', 'heartbeat_interval' => '心跳间隔',
        'weekdays' => '生效星期', 'effective_from' => '生效开始', 'effective_until' => '生效结束',
        'scenario' => '场景', 'limit_rate' => '倍率上限', 'min_rate' => '最低倍率', 'max_rate' => '最高倍率',
        'ip' => 'IP 地址', 'ua' => '客户端标识', 'user_agent' => '客户端标识', 'duration' => '有效时长',
        'handled_at' => '处理时间', 'handled_by' => '处理管理员', 'handled_note' => '处理备注',
        'total_count' => '请求次数', 'blocked_count' => '阻断次数', 'risk_percent' => '风险比例',
        'target_type' => '审核对象类型', 'from_status' => '原状态', 'to_status' => '新状态',
        'operator_id' => '操作管理员', 'reseller_id' => '倒卖商', 'store_slug' => '店铺标识',
        'store_name' => '店铺名称', 'store_description' => '店铺说明', 'reseller_status' => '账号审核状态',
        'store_status' => '店铺审核状态', 'reseller_review_reason' => '账号审核原因', 'store_review_reason' => '店铺审核原因',
        'reseller_reviewed_by' => '账号审核管理员', 'store_reviewed_by' => '店铺审核管理员',
        'reseller_reviewed_at' => '账号审核时间', 'store_reviewed_at' => '店铺审核时间',
        'platform_order_id' => '平台订单', 'amount_snapshot' => '订单金额快照', 'driver' => '支付驱动',
        'payment_id' => '支付方式', 'notify_url' => '回调地址', 'handling_fee_fixed' => '固定手续费',
        'handling_fee_percent' => '手续费比例', 'template_name' => '邮件模板', 'telegram_id' => 'Telegram 账号',
    ],
    'settings' => [
        'app_name' => '网站名称', 'app_description' => '网站介绍', 'app_url' => '网站地址', 'logo' => '网站标志',
        'force_https' => '强制 HTTPS', 'stop_register' => '停止注册', 'site_status' => '站点状态',
        'site_status_title' => '站点状态标题', 'site_status_message' => '站点状态说明', 'site_status_recovery_at' => '预计恢复时间',
        'subscribe_url' => '订阅地址', 'subscribe_path' => '订阅路径', 'tos_url' => '服务条款地址',
        'currency' => '货币', 'currency_symbol' => '货币符号', 'try_out_plan_id' => '试用套餐', 'try_out_hour' => '试用时长',
        'ticket_status' => '工单开关', 'deposit_bounus' => '充值赠送规则',
        'invite_force' => '强制邀请码注册', 'invite_commission' => '邀请佣金比例', 'invite_gen_limit' => '邀请码数量限制',
        'invite_never_expire' => '邀请码永久有效', 'commission_first_time_enable' => '仅首次购买发佣金',
        'commission_auto_check_enable' => '佣金自动审核', 'commission_withdraw_limit' => '最低提现金额',
        'commission_withdraw_method' => '提现方式', 'withdraw_close_enable' => '关闭提现',
        'commission_distribution_enable' => '多级佣金', 'commission_distribution_l1' => '一级佣金',
        'commission_distribution_l2' => '二级佣金', 'commission_distribution_l3' => '三级佣金',
        'plan_change_enable' => '允许更换套餐', 'reset_traffic_method' => '流量重置方式', 'surplus_enable' => '套餐折抵',
        'allow_new_period' => '允许新购周期', 'multi_subscription_enable' => '多订阅',
        'new_order_event_id' => '新购事件', 'renew_order_event_id' => '续费事件', 'change_order_event_id' => '更换套餐事件',
        'show_info_to_server_enable' => '向节点提供用户信息', 'show_subscribe_method' => '订阅展示方式', 'show_subscribe_expire' => '订阅到期提示',
        'frontend_theme' => '前端主题', 'frontend_theme_sidebar' => '侧栏颜色', 'frontend_theme_header' => '顶部颜色',
        'frontend_theme_color' => '主题颜色', 'frontend_background_url' => '背景图片', 'theme_color' => '主题颜色',
        'theme_sidebar' => '侧栏颜色', 'theme_header' => '顶部颜色', 'background_url' => '背景图片',
        'server_api_url' => '节点 API 地址', 'server_pull_interval' => '节点拉取间隔', 'server_push_interval' => '节点上报间隔',
        'server_node_report_min_traffic' => '节点最小上报流量', 'server_device_online_min_traffic' => '设备在线流量阈值',
        'device_limit_mode' => '设备限制模式', 'email_template' => '邮件模板', 'email_host' => '邮件服务器',
        'email_port' => '邮件端口', 'email_username' => '邮件账号', 'email_encryption' => '邮件加密方式', 'email_from_address' => '发件地址',
        'telegram_bot_enable' => 'Telegram 机器人', 'telegram_admin_operation_enable' => '管理员操作通知',
        'telegram_admin_operation_topic_id' => '操作通知话题', 'telegram_account_binding_enable' => 'Telegram 账号绑定',
        'telegram_register_enable' => 'Telegram 注册', 'telegram_register_code_delay' => 'Telegram 注册等待时间',
        'telegram_discuss_id' => 'Telegram 群组', 'telegram_discuss_link' => 'Telegram 群组链接',
        'telegram_subscription_binding_enable' => '订阅群组验证', 'telegram_binding_check_interval' => '群组验证间隔',
        'safe_mode_enable' => '安全模式', 'admin_2fa_force_enable' => '管理员强制二步验证', 'secure_path' => '后台路径',
        'recaptcha_enable' => '人机验证', 'recaptcha_site_key' => '人机验证站点公钥', 'arithmetic_verification_enable' => '算术验证码',
        'register_limit_by_ip_enable' => '注册 IP 限制', 'register_limit_count' => '注册次数限制',
        'register_limit_expire' => '注册限制时长', 'email_verify' => '邮箱验证', 'email_whitelist_enable' => '邮箱白名单',
        'email_whitelist_suffix' => '邮箱后缀白名单', 'email_gmail_limit_enable' => 'Gmail 注册限制',
        'telegram_channel_id' => 'Telegram 频道', 'subscribe_risk_notify_threshold' => '风险通知阈值',
        'password_limit_enable' => '密码错误次数限制', 'password_limit_count' => '密码错误次数',
        'password_limit_expire' => '密码错误限制时长', 'password_reset_required' => '强制修改密码',
        'windows_version' => 'Windows 客户端版本', 'windows_download_url' => 'Windows 客户端下载地址',
        'macos_version' => 'macOS 客户端版本', 'macos_download_url' => 'macOS 客户端下载地址',
        'android_version' => 'Android 客户端版本', 'android_download_url' => 'Android 客户端下载地址',
        'reseller_enable' => '倒卖商功能', 'reseller_allowed_payment_drivers' => '倒卖商支付驱动',
        'payment_secure_driver_allowlist' => '安全支付驱动白名单', 'payment_return_url_allowlist' => '支付返回地址白名单',
        'subscribe_audit_retention_days' => '订阅记录保留天数', 'retention_days' => '订阅记录保留天数',
        'oauth_register_only' => '仅第三方注册', 'oauth_telegram_enable' => 'Telegram 登录',
        'oauth_google_enable' => 'Google 登录', 'oauth_google_client_id' => 'Google 客户端 ID', 'oauth_google_redirect_uri' => 'Google 回调地址',
        'oauth_github_enable' => 'GitHub 登录', 'oauth_github_client_id' => 'GitHub 客户端 ID', 'oauth_github_redirect_uri' => 'GitHub 回调地址',
        'oauth_telegram_login_domain' => 'Telegram 登录域名', 'oauth_telegram_bot_username' => 'Telegram 机器人名称',
        'reward_enable' => '签到与娱乐开关', 'reward_group_enable' => '群组娱乐', 'reward_dice_enable' => '骰子游戏',
        'reward_dice_daily_limit' => '骰子每日次数', 'reward_dice_win_probability' => '骰子中奖概率',
        'reward_dice_payout_multiplier' => '骰子返奖倍率', 'reward_dice_odds' => '骰子赔率', 'reward_dice_win_face' => '骰子中奖点数',
        'reward_slots_enable' => '老虎机游戏', 'reward_slots_daily_limit' => '老虎机每日次数',
        'reward_slots_win_probability' => '老虎机中奖概率', 'reward_slots_payout_multiplier' => '老虎机返奖倍率',
        'reward_slots_odds' => '老虎机赔率', 'reward_slots_jackpot_rate' => '老虎机大奖倍率',
    ],
    'table_fields' => [
        'v2_balance_log' => ['source_id' => '关联来源编号', 'type' => '余额变动类型'],
        'v2_payment_attempt' => ['status' => '支付状态'],
        'v2_user' => ['banned' => '账号状态'],
    ],
    'secrets' => [
        'password' => '密码', 'password_salt' => '密码盐', 'password_algo' => '密码算法', 'token' => '订阅令牌',
        'uuid' => '订阅 UUID', 'code' => '兑换凭据', 'private_key' => '私钥', 'secret' => '密钥',
        'server_token' => '节点通信密钥', 'email_password' => 'SMTP 密码', 'telegram_bot_token' => 'Telegram 机器人令牌',
        'oauth_google_client_secret' => 'Google 客户端密钥', 'oauth_github_client_secret' => 'GitHub 客户端密钥',
        'custom_html' => '自定义 HTML', 'custom_script' => '自定义脚本', 'recaptcha_key' => '人机验证密钥',
        'payload' => '协议配置及凭据', 'auth_data' => '登录凭据', 'session' => '登录会话凭据',
    ],
];
